[project]
name = "pyment"
version = "5.0.0"
description = "Repository containing the pretrained model from the paper \"Learning diverse and generic representations of the brain with multi-task pretraining\" and illustrative scripts for using it"
authors = [
    {name = "Esten Leonardsen", email = "estenleonardsen@proton.me"}
]
license = "CC-BY-NC"
license-files = [
    "LICENSE.md"
]
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "tensorflow==2.21.0",
    "numpy==2.4.3",
    "pandas==3.0.3",
    "typing-extensions==4.15.0",
    "requests==2.32.5",
    "nibabel==5.4.2",
    "matplotlib==3.10.9",
    "tqdm==4.67.3",
    "scikit-learn==1.8.0",
    "xlrd==2.0.2",
    "pydantic==2.12.4",
]

[project.scripts]
pyment-predict = "pyment.cli.predict_from_fastsurfer_folder:main"
pyment-finetune = "pyment.cli.finetune_from_configuration:main"
pyment-verify-mgh = "pyment.cli.verify_mgh_loader:main"

[tool.poetry]
packages = [{include = "pyment"}]
include = [
    {path = "pyproject.toml", format = "sdist"}
]

[tool.ruff]
line-length = 80
target-version = "py313"
exclude = [".act", "checkpoints"]

[tool.ruff.lint]
select = ["E", "F", "W", "I", "G"]

[tool.ruff.lint.pycodestyle]
max-doc-length = 72

[tool.ruff.format]
quote-style = "single"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ruff (>=0.15.13,<0.16.0)",
    "pre-commit (>=4.6.0,<5.0.0)",
    "pytest (>=9.0.3,<10.0.0)"
]
