FROM freesurfer/freesurfer:7.2.0

RUN mkdir /src

COPY pyment /src/pyment
COPY scripts /src/scripts
COPY requirements.txt /src/requirements.txt
COPY setup.py /src/setup.py

WORKDIR /src

RUN yum -y upgrade
RUN yum -y install epel-release
RUN yum -y install python3.9 python-pip
#RUN pip install --upgrade pip
#RUN pip install -r requirements.txt --no-cache-dir
#RUN pip install tensorflow==2.5.0
#RUN pip install -e /src

CMD /bin/bash

#CMD python /src/scripts/predict_brain_age.py \
#        -f /images \
#        -m sfcn-reg \
#        -w brain-age \
#        -b 1 \
#        -t 4 \
#        -n \
#        -d /predictions/predictions.csv \
#        2>&1 | tee /predictions/logs.txt