name: Run test suite

on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

jobs:
  docker-tests:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build test image
        run: docker build -f docker/tests.Dockerfile -t pyment-tests .

      - name: Run tests
        run: docker run --rm pyment-tests
